-- AlterTable
ALTER TABLE "sales" ADD COLUMN     "trading_day_id" UUID;

-- CreateTable
CREATE TABLE "trading_days" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "store_id" UUID NOT NULL,
    "status" TEXT NOT NULL,
    "starting_float_minor_units" BIGINT NOT NULL,
    "counted_cash_minor_units" BIGINT,
    "expected_cash_minor_units" BIGINT,
    "variance_minor_units" BIGINT,
    "closed_at" TIMESTAMPTZ,
    "reopened_at" TIMESTAMPTZ,
    "reopened_by" UUID,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" UUID NOT NULL,

    CONSTRAINT "trading_days_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "trading_days_tenant_id_store_id_status_idx" ON "trading_days"("tenant_id", "store_id", "status");

-- AddForeignKey
ALTER TABLE "sales" ADD CONSTRAINT "sales_trading_day_id_fkey" FOREIGN KEY ("trading_day_id") REFERENCES "trading_days"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "trading_days" ADD CONSTRAINT "trading_days_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "trading_days" ADD CONSTRAINT "trading_days_store_id_fkey" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "trading_days" ADD CONSTRAINT "trading_days_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "trading_days" ADD CONSTRAINT "trading_days_reopened_by_fkey" FOREIGN KEY ("reopened_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Hand-edited addition, not generated by `prisma migrate diff`: Prisma's schema DSL has no partial-
-- index syntax. This is the actual mechanism behind "one open trading day per store" —
-- docs/modules/trading-day/specification.md §2/§3 — a correctness guard against two concurrent
-- POST /trading-days/open calls racing, not merely a query-speed optimisation the way
-- user_store_roles' own (non-unique) partial-index substitute was.
CREATE UNIQUE INDEX "trading_days_one_open_per_store" ON "trading_days"("tenant_id", "store_id") WHERE "status" = 'open';
