-- Hand-edited, not generated by `prisma migrate diff`: Prisma's schema DSL has no operator-class
-- syntax for GIN/trigram indexes. `products/repository.ts#listProducts`'s real search is a
-- middle-match `ILIKE '%text%'` scan against `name` OR `sku` (Sprint 69/70's own documentation
-- audit found the plain B-tree index this schema previously assumed would help does nothing for a
-- `contains` pattern — only left-anchored `LIKE 'text%'` benefits from a plain/`text_pattern_ops`
-- index). `pg_trgm`'s trigram GIN indexes are Postgres's actual mechanism for accelerating
-- `ILIKE`/`LIKE '%...%'`, ships in the standard `postgres` contrib modules (available on Supabase
-- without a paid add-on, matching this project's free/open-source-first constraint), and needs no
-- application-code change — `contains`/`mode: "insensitive"` already produces exactly the pattern
-- these indexes accelerate.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX "products_name_trgm_idx" ON "products" USING GIN ("name" gin_trgm_ops);
CREATE INDEX "products_sku_trgm_idx" ON "products" USING GIN ("sku" gin_trgm_ops);
