import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';

import 'tables/categories.dart';
import 'tables/customers.dart';
import 'tables/device_identity.dart';
import 'tables/local_provisional_sequence.dart';
import 'tables/outbound_queue.dart';
import 'tables/paired_printer_cache.dart';
import 'tables/products.dart';
import 'tables/return_line_items.dart';
import 'tables/returns.dart';
import 'tables/sale_line_items.dart';
import 'tables/sale_payments.dart';
import 'tables/sales.dart';
import 'tables/shop_settings_cache.dart';
import 'tables/stock_movements.dart';
import 'tables/store_context.dart';
import 'tables/sync_cursors.dart';
import 'tables/units.dart';

part 'database.g.dart';

/// M0's local database — outbound_queue plus the minimal products/sales/
/// stock_movements slice backlog.md item 4 scopes, plus `StoreContext`
/// (Sprint 08, a local cache of the device's own `store_id`),
/// `DeviceIdentity`/`LocalProvisionalSequence` (Sprint 09, ADR-0008's local
/// invoice-numbering half), `Categories`/`Units` (Sprint 20, M1's own
/// backlog item 4 — local read caches, see their own table docstrings for
/// why they aren't queued via `outbound_queue` like `Products` is), and
/// `Customers` (Sprint 32, M3 item 2 — unlike Categories/Units, genuinely
/// offline-writable via `outbound_queue`, see customers.dart's own
/// docstring). `Returns`/`ReturnLineItems` (Sprint 34, M3 item 4 — same
/// genuinely-offline-writable shape as `Customers`, see returns.dart's own
/// docstring). Every other local table in schema-local.md (the
/// server-authoritative caches, ...) is added by the sprint that actually
/// needs it, not stubbed here ahead of the backlog.
@DriftDatabase(
  tables: [
    Categories,
    Customers,
    DeviceIdentity,
    LocalProvisionalSequence,
    OutboundQueue,
    PairedPrinterCache,
    Products,
    ReturnLineItems,
    Returns,
    Sales,
    SaleLineItems,
    SalePayments,
    ShopSettingsCache,
    StockMovements,
    StoreContext,
    SyncCursors,
    Units,
  ],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase([QueryExecutor? executor]) : super(executor ?? _openConnection(null));

  /// Sprint 48 (docs/12-security/data-protection.md §3, OWASP M9) — the real production entry
  /// point. Opens the local database through the SQLCipher-enabled `sqlite3` build selected in
  /// `pubspec.yaml`'s `hooks.user_defines` with [encryptionKey] set via `PRAGMA key` before any
  /// other statement runs, on a raw hex key already generated by
  /// `getOrCreateDatabaseEncryptionKey` — see that function's own docstring for why the raw-key
  /// form (`x'...'`) is used instead of a passphrase.
  AppDatabase.encrypted(String encryptionKey) : super(_openConnection(encryptionKey));

  @override
  int get schemaVersion => 9;

  // The first schema change was Sprint 20 (schemaVersion 1 -> 2); Sprint 21
  // (backlog.md item 5) adds `sku`/`barcode` to `products` for the till's
  // offline barcode-scan lookup; Sprint 30 (M2 item 6, Hold/Resume) adds
  // `sales.created_at` — see sales.dart's own comment for why; Sprint 32 (M3
  // item 2) adds the `Customers` table and `sales.customer_id`; Sprint 34 (M3
  // item 4) adds the `Returns`/`ReturnLineItems` tables; Sprint 36 (M4 item 1)
  // adds the `SyncCursors` table for stock_movements/sales pull resumability;
  // Sprint 37 (M4 item 2) adds `ShopSettingsCache` (the low-stock threshold
  // plus the Reports role-probe result); Sprint 39 (M4 item 4) adds
  // `ShopSettingsCache.footerMessage` and the new `PairedPrinterCache` table.
  // Same non-destructive-migration
  // discipline — a real founder device already
  // has real local data. Existing `'completed'` rows get `created_at`
  // backfilled from `completed_at` (a reasonable historical approximation,
  // not a precision claim) rather than left null.
  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (m) => m.createAll(),
    onUpgrade: (m, from, to) async {
      if (from < 2) {
        await m.createTable(categories);
        await m.createTable(units);
        await m.addColumn(products, products.categoryId);
        await m.addColumn(products, products.unitId);
      }
      if (from < 3) {
        await m.addColumn(products, products.sku);
        await m.addColumn(products, products.barcode);
      }
      if (from < 4) {
        await m.addColumn(sales, sales.createdAt);
        await customStatement(
          'UPDATE sales SET created_at = completed_at WHERE created_at IS NULL AND completed_at IS NOT NULL',
        );
      }
      if (from < 5) {
        await m.createTable(customers);
        await m.addColumn(sales, sales.customerId);
      }
      if (from < 6) {
        await m.createTable(returns);
        await m.createTable(returnLineItems);
      }
      if (from < 7) {
        await m.createTable(syncCursors);
      }
      if (from < 8) {
        await m.createTable(shopSettingsCache);
      }
      if (from < 9) {
        await m.addColumn(shopSettingsCache, shopSettingsCache.footerMessage);
        await m.createTable(pairedPrinterCache);
      }
    },
  );

  static QueryExecutor _openConnection(String? encryptionKey) {
    return driftDatabase(
      name: 'smart_pos_x',
      native: encryptionKey == null
          ? null
          : DriftNativeOptions(
              setup: (db) => db.execute("PRAGMA key = \"x'$encryptionKey'\""),
            ),
    );
  }
}
